server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:4200,http://localhost:80
file:
  upload-dir: /home/runner/work/rest-api/api_rest-1/upload-dir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 7200000  
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/rest_api?useTimezone=true&serverTimezone=UTC
      username: root
      password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB   
      max-request-size: 215MB     
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
